package com.real.logicserver.social.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import com.real.logicserver.social.model.Message;

@Repository
@Mapper
public interface MessageMapper {
	
	List<Message> selectByUserId(Integer userId);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer msgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	Message selectByPrimaryKey(Integer msgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Message record);

	
}