package com.real.logicserver.social.model;

import java.util.Date;

public class Message {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.msg_id
	 * @mbg.generated
	 */
	private Integer msgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.content
	 * @mbg.generated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.sender_id
	 * @mbg.generated
	 */
	private String senderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.receiver_id
	 * @mbg.generated
	 */
	private String receiverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.msg_type
	 * @mbg.generated
	 */
	private Integer msgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.msg_time
	 * @mbg.generated
	 */
	private Date msgTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.is_room
	 * @mbg.generated
	 */
	private Boolean isRoom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.status
	 * @mbg.generated
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.msg_id
	 * @return  the value of message.msg_id
	 * @mbg.generated
	 */
	public Integer getMsgId() {
		return msgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.msg_id
	 * @param msgId  the value for message.msg_id
	 * @mbg.generated
	 */
	public void setMsgId(Integer msgId) {
		this.msgId = msgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.content
	 * @return  the value of message.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.content
	 * @param content  the value for message.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.sender_id
	 * @return  the value of message.sender_id
	 * @mbg.generated
	 */
	public String getSenderId() {
		return senderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.sender_id
	 * @param senderId  the value for message.sender_id
	 * @mbg.generated
	 */
	public void setSenderId(String senderId) {
		this.senderId = senderId == null ? null : senderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.receiver_id
	 * @return  the value of message.receiver_id
	 * @mbg.generated
	 */
	public String getReceiverId() {
		return receiverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.receiver_id
	 * @param receiverId  the value for message.receiver_id
	 * @mbg.generated
	 */
	public void setReceiverId(String receiverId) {
		this.receiverId = receiverId == null ? null : receiverId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.msg_type
	 * @return  the value of message.msg_type
	 * @mbg.generated
	 */
	public Integer getMsgType() {
		return msgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.msg_type
	 * @param msgType  the value for message.msg_type
	 * @mbg.generated
	 */
	public void setMsgType(Integer msgType) {
		this.msgType = msgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.msg_time
	 * @return  the value of message.msg_time
	 * @mbg.generated
	 */
	public Date getMsgTime() {
		return msgTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.msg_time
	 * @param msgTime  the value for message.msg_time
	 * @mbg.generated
	 */
	public void setMsgTime(Date msgTime) {
		this.msgTime = msgTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.is_room
	 * @return  the value of message.is_room
	 * @mbg.generated
	 */
	public Boolean getIsRoom() {
		return isRoom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.is_room
	 * @param isRoom  the value for message.is_room
	 * @mbg.generated
	 */
	public void setIsRoom(Boolean isRoom) {
		this.isRoom = isRoom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.status
	 * @return  the value of message.status
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.status
	 * @param status  the value for message.status
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}
}