package com.real.logicserver.social.friend.model;

public class UserFriend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.user_friend_id
     *
     * @mbg.generated
     */
    private Integer userFriendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.fr_user_id
     *
     * @mbg.generated
     */
    private Integer frUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.fr_user_type
     *
     * @mbg.generated
     */
    private String frUserType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.user_friend_id
     *
     * @return the value of user_friend.user_friend_id
     *
     * @mbg.generated
     */
    public Integer getUserFriendId() {
        return userFriendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.user_friend_id
     *
     * @param userFriendId the value for user_friend.user_friend_id
     *
     * @mbg.generated
     */
    public void setUserFriendId(Integer userFriendId) {
        this.userFriendId = userFriendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.user_id
     *
     * @return the value of user_friend.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.user_id
     *
     * @param userId the value for user_friend.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.fr_user_id
     *
     * @return the value of user_friend.fr_user_id
     *
     * @mbg.generated
     */
    public Integer getFrUserId() {
        return frUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.fr_user_id
     *
     * @param frUserId the value for user_friend.fr_user_id
     *
     * @mbg.generated
     */
    public void setFrUserId(Integer frUserId) {
        this.frUserId = frUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.fr_user_type
     *
     * @return the value of user_friend.fr_user_type
     *
     * @mbg.generated
     */
    public String getFrUserType() {
        return frUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.fr_user_type
     *
     * @param frUserType the value for user_friend.fr_user_type
     *
     * @mbg.generated
     */
    public void setFrUserType(String frUserType) {
        this.frUserType = frUserType == null ? null : frUserType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.mark
     *
     * @return the value of user_friend.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.mark
     *
     * @param mark the value for user_friend.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}