package com.real.logicserver.meeting.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;
import org.apache.ibatis.annotations.Mapper;

public class Meeting {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting.me_id
	 * @mbg.generated
	 */
	private Integer meId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting.start_time
	 * @mbg.generated
	 */

	@JSONField (format="yyyy-MM-dd HH:mm:ss")
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting.end_time
	 * @mbg.generated
	 */

	@JSONField (format="yyyy-MM-dd HH:mm:ss")
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting.place
	 * @mbg.generated
	 */
	private String place;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting.num
	 * @mbg.generated
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting.desc
	 * @mbg.generated
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting.logo
	 * @mbg.generated
	 */
	private String logo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting.type_id
	 * @mbg.generated
	 */
	private Integer typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting.is_aduit
	 * @mbg.generated
	 */
	private String isAduit;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting.me_id
	 * @return  the value of meeting.me_id
	 * @mbg.generated
	 */
	public Integer getMeId() {
		return meId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting.me_id
	 * @param meId  the value for meeting.me_id
	 * @mbg.generated
	 */
	public void setMeId(Integer meId) {
		this.meId = meId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting.start_time
	 * @return  the value of meeting.start_time
	 * @mbg.generated
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting.start_time
	 * @param startTime  the value for meeting.start_time
	 * @mbg.generated
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting.end_time
	 * @return  the value of meeting.end_time
	 * @mbg.generated
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting.end_time
	 * @param endTime  the value for meeting.end_time
	 * @mbg.generated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting.place
	 * @return  the value of meeting.place
	 * @mbg.generated
	 */
	public String getPlace() {
		return place;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting.place
	 * @param place  the value for meeting.place
	 * @mbg.generated
	 */
	public void setPlace(String place) {
		this.place = place == null ? null : place.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting.num
	 * @return  the value of meeting.num
	 * @mbg.generated
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting.num
	 * @param num  the value for meeting.num
	 * @mbg.generated
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting.desc
	 * @return  the value of meeting.desc
	 * @mbg.generated
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting.desc
	 * @param desc  the value for meeting.desc
	 * @mbg.generated
	 */
	public void setDesc(String desc) {
		this.desc = desc == null ? null : desc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting.title
	 * @return  the value of meeting.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting.title
	 * @param title  the value for meeting.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting.logo
	 * @return  the value of meeting.logo
	 * @mbg.generated
	 */
	public String getLogo() {
		return logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting.logo
	 * @param logo  the value for meeting.logo
	 * @mbg.generated
	 */
	public void setLogo(String logo) {
		this.logo = logo == null ? null : logo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting.type_id
	 * @return  the value of meeting.type_id
	 * @mbg.generated
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting.type_id
	 * @param typeId  the value for meeting.type_id
	 * @mbg.generated
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting.is_aduit
	 * @return  the value of meeting.is_aduit
	 * @mbg.generated
	 */
	public String getIsAduit() {
		return isAduit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting.is_aduit
	 * @param isAduit  the value for meeting.is_aduit
	 * @mbg.generated
	 */
	public void setIsAduit(String isAduit) {
		this.isAduit = isAduit == null ? null : isAduit.trim();
	}
}