package com.real.logicserver.meeting.model;

public class MeetingRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_role.meeting_role_id
     *
     * @mbg.generated
     */
    private Integer meetingRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_role.me_id
     *
     * @mbg.generated
     */
    private Integer meId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_role.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_role.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_role.meeting_role_id
     *
     * @return the value of meeting_role.meeting_role_id
     *
     * @mbg.generated
     */
    public Integer getMeetingRoleId() {
        return meetingRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_role.meeting_role_id
     *
     * @param meetingRoleId the value for meeting_role.meeting_role_id
     *
     * @mbg.generated
     */
    public void setMeetingRoleId(Integer meetingRoleId) {
        this.meetingRoleId = meetingRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_role.me_id
     *
     * @return the value of meeting_role.me_id
     *
     * @mbg.generated
     */
    public Integer getMeId() {
        return meId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_role.me_id
     *
     * @param meId the value for meeting_role.me_id
     *
     * @mbg.generated
     */
    public void setMeId(Integer meId) {
        this.meId = meId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_role.user_id
     *
     * @return the value of meeting_role.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_role.user_id
     *
     * @param userId the value for meeting_role.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_role.role_id
     *
     * @return the value of meeting_role.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_role.role_id
     *
     * @param roleId the value for meeting_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}