package com.real.logicserver.meeting.model;

import java.util.Date;

public class MeetingHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_history.meeting_history_id
     *
     * @mbg.generated
     */
    private Integer meetingHistoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_history.meeting_id
     *
     * @mbg.generated
     */
    private Integer meetingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_history.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_history.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_history.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_history.meeting_status
     *
     * @mbg.generated
     */
    private Integer meetingStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_history.meeting_history_id
     *
     * @return the value of meeting_history.meeting_history_id
     *
     * @mbg.generated
     */
    public Integer getMeetingHistoryId() {
        return meetingHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_history.meeting_history_id
     *
     * @param meetingHistoryId the value for meeting_history.meeting_history_id
     *
     * @mbg.generated
     */
    public void setMeetingHistoryId(Integer meetingHistoryId) {
        this.meetingHistoryId = meetingHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_history.meeting_id
     *
     * @return the value of meeting_history.meeting_id
     *
     * @mbg.generated
     */
    public Integer getMeetingId() {
        return meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_history.meeting_id
     *
     * @param meetingId the value for meeting_history.meeting_id
     *
     * @mbg.generated
     */
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_history.user_id
     *
     * @return the value of meeting_history.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_history.user_id
     *
     * @param userId the value for meeting_history.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_history.create_time
     *
     * @return the value of meeting_history.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_history.create_time
     *
     * @param createTime the value for meeting_history.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_history.update_time
     *
     * @return the value of meeting_history.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_history.update_time
     *
     * @param updateTime the value for meeting_history.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_history.meeting_status
     *
     * @return the value of meeting_history.meeting_status
     *
     * @mbg.generated
     */
    public Integer getMeetingStatus() {
        return meetingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_history.meeting_status
     *
     * @param meetingStatus the value for meeting_history.meeting_status
     *
     * @mbg.generated
     */
    public void setMeetingStatus(Integer meetingStatus) {
        this.meetingStatus = meetingStatus;
    }
}