package com.real.logicserver.meeting.model;

public class MeetingType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting_type.meeting_type_id
	 * @mbg.generated
	 */
	private Integer meetingTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting_type.meeting_type_name
	 * @mbg.generated
	 */
	private String meetingTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting_type.meeting_type_logo
	 * @mbg.generated
	 */
	private String meetingTypeLogo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting_type.create_person
	 * @mbg.generated
	 */
	private Integer createPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting_type.update_person
	 * @mbg.generated
	 */
	private Integer updatePerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meeting_type.desc
	 * @mbg.generated
	 */
	private String desc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting_type.meeting_type_id
	 * @return  the value of meeting_type.meeting_type_id
	 * @mbg.generated
	 */
	public Integer getMeetingTypeId() {
		return meetingTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting_type.meeting_type_id
	 * @param meetingTypeId  the value for meeting_type.meeting_type_id
	 * @mbg.generated
	 */
	public void setMeetingTypeId(Integer meetingTypeId) {
		this.meetingTypeId = meetingTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting_type.meeting_type_name
	 * @return  the value of meeting_type.meeting_type_name
	 * @mbg.generated
	 */
	public String getMeetingTypeName() {
		return meetingTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting_type.meeting_type_name
	 * @param meetingTypeName  the value for meeting_type.meeting_type_name
	 * @mbg.generated
	 */
	public void setMeetingTypeName(String meetingTypeName) {
		this.meetingTypeName = meetingTypeName == null ? null : meetingTypeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting_type.meeting_type_logo
	 * @return  the value of meeting_type.meeting_type_logo
	 * @mbg.generated
	 */
	public String getMeetingTypeLogo() {
		return meetingTypeLogo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting_type.meeting_type_logo
	 * @param meetingTypeLogo  the value for meeting_type.meeting_type_logo
	 * @mbg.generated
	 */
	public void setMeetingTypeLogo(String meetingTypeLogo) {
		this.meetingTypeLogo = meetingTypeLogo == null ? null : meetingTypeLogo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting_type.create_person
	 * @return  the value of meeting_type.create_person
	 * @mbg.generated
	 */
	public Integer getCreatePerson() {
		return createPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting_type.create_person
	 * @param createPerson  the value for meeting_type.create_person
	 * @mbg.generated
	 */
	public void setCreatePerson(Integer createPerson) {
		this.createPerson = createPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting_type.update_person
	 * @return  the value of meeting_type.update_person
	 * @mbg.generated
	 */
	public Integer getUpdatePerson() {
		return updatePerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting_type.update_person
	 * @param updatePerson  the value for meeting_type.update_person
	 * @mbg.generated
	 */
	public void setUpdatePerson(Integer updatePerson) {
		this.updatePerson = updatePerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meeting_type.desc
	 * @return  the value of meeting_type.desc
	 * @mbg.generated
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meeting_type.desc
	 * @param desc  the value for meeting_type.desc
	 * @mbg.generated
	 */
	public void setDesc(String desc) {
		this.desc = desc == null ? null : desc.trim();
	}
}