package com.real.logicserver.meeting.model;

public class MeetingDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_detail.meeting_detail_id
     *
     * @mbg.generated
     */
    private Integer meetingDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_detail.participants_number
     *
     * @mbg.generated
     */
    private Integer participantsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_detail.participants_sum
     *
     * @mbg.generated
     */
    private Integer participantsSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_detail.meeting_id
     *
     * @mbg.generated
     */
    private Integer meetingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_detail.meeting_detail_id
     *
     * @return the value of meeting_detail.meeting_detail_id
     *
     * @mbg.generated
     */
    public Integer getMeetingDetailId() {
        return meetingDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_detail.meeting_detail_id
     *
     * @param meetingDetailId the value for meeting_detail.meeting_detail_id
     *
     * @mbg.generated
     */
    public void setMeetingDetailId(Integer meetingDetailId) {
        this.meetingDetailId = meetingDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_detail.participants_number
     *
     * @return the value of meeting_detail.participants_number
     *
     * @mbg.generated
     */
    public Integer getParticipantsNumber() {
        return participantsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_detail.participants_number
     *
     * @param participantsNumber the value for meeting_detail.participants_number
     *
     * @mbg.generated
     */
    public void setParticipantsNumber(Integer participantsNumber) {
        this.participantsNumber = participantsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_detail.participants_sum
     *
     * @return the value of meeting_detail.participants_sum
     *
     * @mbg.generated
     */
    public Integer getParticipantsSum() {
        return participantsSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_detail.participants_sum
     *
     * @param participantsSum the value for meeting_detail.participants_sum
     *
     * @mbg.generated
     */
    public void setParticipantsSum(Integer participantsSum) {
        this.participantsSum = participantsSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_detail.meeting_id
     *
     * @return the value of meeting_detail.meeting_id
     *
     * @mbg.generated
     */
    public Integer getMeetingId() {
        return meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_detail.meeting_id
     *
     * @param meetingId the value for meeting_detail.meeting_id
     *
     * @mbg.generated
     */
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }
}