package com.real.logicserver.quiz.repository;

import com.real.logicserver.quiz.model.Choices;

public interface ChoicesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer choicesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    int insert(Choices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    int insertSelective(Choices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    Choices selectByPrimaryKey(Integer choicesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Choices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Choices record);
}