package com.real.logicserver.quiz.repository;

import com.real.logicserver.quiz.model.ChoiceAnswers;

public interface ChoiceAnswersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_answers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer choiceAnswersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_answers
     *
     * @mbg.generated
     */
    int insert(ChoiceAnswers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_answers
     *
     * @mbg.generated
     */
    int insertSelective(ChoiceAnswers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_answers
     *
     * @mbg.generated
     */
    ChoiceAnswers selectByPrimaryKey(Integer choiceAnswersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_answers
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChoiceAnswers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice_answers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChoiceAnswers record);
}