package com.real.logicserver.quiz.repository;

import com.real.logicserver.meeting.model.MeetingType;

public interface MeetingTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_type
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer meetingTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_type
	 * @mbg.generated
	 */
	int insert(MeetingType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_type
	 * @mbg.generated
	 */
	int insertSelective(MeetingType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_type
	 * @mbg.generated
	 */
	MeetingType selectByPrimaryKey(Integer meetingTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_type
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MeetingType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_type
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MeetingType record);
}