package com.real.logicserver.quiz.repository;

import com.real.logicserver.quiz.model.Questions;

public interface QuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer questionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated
     */
    int insert(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated
     */
    int insertSelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated
     */
    Questions selectByPrimaryKey(Integer questionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Questions record);
}