package com.real.logicserver.quiz.model;

public class Choices {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choices.choices_id
     *
     * @mbg.generated
     */
    private Integer choicesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choices.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choices.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choices.choices_id
     *
     * @return the value of choices.choices_id
     *
     * @mbg.generated
     */
    public Integer getChoicesId() {
        return choicesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choices.choices_id
     *
     * @param choicesId the value for choices.choices_id
     *
     * @mbg.generated
     */
    public void setChoicesId(Integer choicesId) {
        this.choicesId = choicesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choices.question_id
     *
     * @return the value of choices.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choices.question_id
     *
     * @param questionId the value for choices.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choices.description
     *
     * @return the value of choices.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choices.description
     *
     * @param description the value for choices.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}