package com.real.logicserver.quiz.model;

public class ChoiceAnswers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice_answers.choice_answers_id
     *
     * @mbg.generated
     */
    private Integer choiceAnswersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice_answers.session_id
     *
     * @mbg.generated
     */
    private Integer sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice_answers.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice_answers.choice_id
     *
     * @mbg.generated
     */
    private Integer choiceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice_answers.choice_answers_id
     *
     * @return the value of choice_answers.choice_answers_id
     *
     * @mbg.generated
     */
    public Integer getChoiceAnswersId() {
        return choiceAnswersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice_answers.choice_answers_id
     *
     * @param choiceAnswersId the value for choice_answers.choice_answers_id
     *
     * @mbg.generated
     */
    public void setChoiceAnswersId(Integer choiceAnswersId) {
        this.choiceAnswersId = choiceAnswersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice_answers.session_id
     *
     * @return the value of choice_answers.session_id
     *
     * @mbg.generated
     */
    public Integer getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice_answers.session_id
     *
     * @param sessionId the value for choice_answers.session_id
     *
     * @mbg.generated
     */
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice_answers.question_id
     *
     * @return the value of choice_answers.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice_answers.question_id
     *
     * @param questionId the value for choice_answers.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice_answers.choice_id
     *
     * @return the value of choice_answers.choice_id
     *
     * @mbg.generated
     */
    public Integer getChoiceId() {
        return choiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice_answers.choice_id
     *
     * @param choiceId the value for choice_answers.choice_id
     *
     * @mbg.generated
     */
    public void setChoiceId(Integer choiceId) {
        this.choiceId = choiceId;
    }
}