package com.real.logicserver.quiz.model;

public class Questions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.questions_id
     *
     * @mbg.generated
     */
    private Integer questionsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.form_id
     *
     * @mbg.generated
     */
    private Integer formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.question
     *
     * @mbg.generated
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.answer_type
     *
     * @mbg.generated
     */
    private String answerType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.questions_id
     *
     * @return the value of questions.questions_id
     *
     * @mbg.generated
     */
    public Integer getQuestionsId() {
        return questionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.questions_id
     *
     * @param questionsId the value for questions.questions_id
     *
     * @mbg.generated
     */
    public void setQuestionsId(Integer questionsId) {
        this.questionsId = questionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.form_id
     *
     * @return the value of questions.form_id
     *
     * @mbg.generated
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.form_id
     *
     * @param formId the value for questions.form_id
     *
     * @mbg.generated
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.question
     *
     * @return the value of questions.question
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.question
     *
     * @param question the value for questions.question
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.answer_type
     *
     * @return the value of questions.answer_type
     *
     * @mbg.generated
     */
    public String getAnswerType() {
        return answerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.answer_type
     *
     * @param answerType the value for questions.answer_type
     *
     * @mbg.generated
     */
    public void setAnswerType(String answerType) {
        this.answerType = answerType == null ? null : answerType.trim();
    }
}