package com.real.logicserver.quiz.model;

public class TextAnswers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_answers.text_answers_id
     *
     * @mbg.generated
     */
    private Integer textAnswersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_answers.session_id
     *
     * @mbg.generated
     */
    private Integer sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_answers.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_answers.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_answers.text_answers_id
     *
     * @return the value of text_answers.text_answers_id
     *
     * @mbg.generated
     */
    public Integer getTextAnswersId() {
        return textAnswersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_answers.text_answers_id
     *
     * @param textAnswersId the value for text_answers.text_answers_id
     *
     * @mbg.generated
     */
    public void setTextAnswersId(Integer textAnswersId) {
        this.textAnswersId = textAnswersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_answers.session_id
     *
     * @return the value of text_answers.session_id
     *
     * @mbg.generated
     */
    public Integer getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_answers.session_id
     *
     * @param sessionId the value for text_answers.session_id
     *
     * @mbg.generated
     */
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_answers.question_id
     *
     * @return the value of text_answers.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_answers.question_id
     *
     * @param questionId the value for text_answers.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_answers.content
     *
     * @return the value of text_answers.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_answers.content
     *
     * @param content the value for text_answers.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}