package com.real.logicserver.meeting.repository;

import com.real.logicserver.meeting.model.MeetingUser;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface MeetingUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer meetingUserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_user
	 * @mbg.generated
	 */
	int insert(MeetingUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_user
	 * @mbg.generated
	 */
	int insertSelective(MeetingUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_user
	 * @mbg.generated
	 */
	MeetingUser selectByPrimaryKey(Integer meetingUserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_user
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MeetingUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MeetingUser record);
}