package com.real.logicserver.meeting.repository;

import com.real.logicserver.meeting.model.MeetingHistory;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface MeetingHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_history
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer meetingHistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_history
	 * @mbg.generated
	 */
	int insert(MeetingHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_history
	 * @mbg.generated
	 */
	int insertSelective(MeetingHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_history
	 * @mbg.generated
	 */
	MeetingHistory selectByPrimaryKey(Integer meetingHistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_history
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MeetingHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_history
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MeetingHistory record);
}