package com.real.logicserver.meeting.repository;

import com.real.logicserver.meeting.model.MeetingRole;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface MeetingRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer meetingRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_role
     *
     * @mbg.generated
     */
    int insert(MeetingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_role
     *
     * @mbg.generated
     */
    int insertSelective(MeetingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_role
     *
     * @mbg.generated
     */
    MeetingRole selectByPrimaryKey(Integer meetingRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MeetingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MeetingRole record);
}