package com.real.logicserver.meeting.repository;

import com.real.logicserver.meeting.model.MeetingSigned;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface MeetingSignedMapper {

	
	List<MeetingSigned> getMeetingSignedMembers(Integer meetingId);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_signed
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer meetingSignedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_signed
	 * @mbg.generated
	 */
	int insert(MeetingSigned record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_signed
	 * @mbg.generated
	 */
	int insertSelective(MeetingSigned record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_signed
	 * @mbg.generated
	 */
	MeetingSigned selectByPrimaryKey(Integer meetingSignedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_signed
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MeetingSigned record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_signed
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MeetingSigned record);
}