package com.real.logicserver.meeting.repository;

import com.real.logicserver.meeting.model.MeetingTag;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface MeetingTagMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_tag
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer meetingTagId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_tag
	 * @mbg.generated
	 */
	int insert(MeetingTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_tag
	 * @mbg.generated
	 */
	int insertSelective(MeetingTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_tag
	 * @mbg.generated
	 */
	MeetingTag selectByPrimaryKey(Integer meetingTagId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_tag
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MeetingTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_tag
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MeetingTag record);
}