package com.real.logicserver.social.friend.repository;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import com.real.logicserver.social.friend.model.UserFriend;

@Repository
@Mapper
public interface UserFriendMapper {
	
	int deleteByUserId(Integer userId,Integer friendId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userFriendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated
     */
    int insert(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated
     */
    int insertSelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated
     */
    UserFriend selectByPrimaryKey(Integer userFriendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserFriend record);
}